version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    container_name: api
    volumes:
      - ./api:/api
      - /api/node_modules
  dashboard:
    build:
      context: ./dashboard
    ports:
      - "5002:5002"
    container_name: dashboard
    stdin_open: true
    volumes:
      - ./dashboard:/dashboard
      - /dashboard/node_modules
